


-----------------------------------
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(300)		NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일(ID 역할)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호(암호화)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';
	
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화 번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴 여부(Y,N)';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1:일반, 2:관리자)';

-- 회원 번호 시퀀스 만들기
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

SELECT SEQ_MEMBER_NO.CURRVAL FROM DUAL;

ALTER SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1;

ALTER SEQUENCE SEQ_MEMBER_NO RESTART START WITH 1;

-- 샘플 회원 데이터 삽입
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 
			 'user01@kh.or.kr',
			 'pass01!',
			 '유저일',
			 '01012341234',
			 NULL,
			 NULL,
			 DEFAULT,
			 DEFAULT,
			 DEFAULT
);

SELECT * FROM MEMBER;

DELETE FROM MEMBER WHERE MEMBER_NO = 1;

COMMIT;

-- user01 회원의 비밀번호 암호화하여 저장
UPDATE "MEMBER" SET
MEMBER_PW = '$2a$10$KJNTXIhS4/WQVe7cuEzgt.nACK8kFXnY6G9fzOnOGWLNSyEjrbCwC'
WHERE MEMBER_NO = 1;

UPDATE "MEMBER" SET AUTHORITY = 2
WHERE MEMBER_NO = 2;


------------ (삭제된 회원 복구) ----------------------
UPDATE "MEMBER"
SET MEMBER_DEL_FL = 'N'
WHERE MEMBER_NO = 1;
------------------------------------------------------

-----------------------------------------

/* 이메일, 인증키 저장 테이블 생성 */
CREATE TABLE "TB_AUTH_KEY"(
	"KEY_NO"    NUMBER PRIMARY KEY,
	"EMAIL"	    NVARCHAR2(50) NOT NULL,
	"AUTH_KEY"  CHAR(6)	NOT NULL,
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN "TB_AUTH_KEY"."KEY_NO"      IS '인증키 구분 번호(시퀀스)';
COMMENT ON COLUMN "TB_AUTH_KEY"."EMAIL"       IS '인증 이메일';
COMMENT ON COLUMN "TB_AUTH_KEY"."AUTH_KEY"    IS '인증 번호';
COMMENT ON COLUMN "TB_AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';

CREATE SEQUENCE SEQ_KEY_NO NOCACHE; -- 인증키 구분 번호 시퀀스


SELECT * FROM "TB_AUTH_KEY";

COMMIT;


------------------------------------------


-- 파일 
CREATE TABLE "UPLOAD_FILE" (
	"FILE_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NOT NULL,
	"FILE_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"FILE_RENAME"	VARCHAR2(100)		NOT NULL,
	"FILE_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_NO" IS '파일 번호(PK)';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_PATH" IS '파일 요청 경로';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_ORIGINAL_NAME" IS '파일 원본명';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_RENAME" IS '파일 변경명';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_UPLOAD_DATE" IS '업로드 날짜';

COMMENT ON COLUMN "UPLOAD_FILE"."MEMBER_NO" IS '업로드한 회원 번호';
		
-- 시퀀스 SEQ_FILE_NO 생성		
CREATE SEQUENCE SEQ_FILE_NO NOCACHE;

SELECT * FROM "UPLOAD_FILE";

	-- 
	SELECT FILE_NO, FILE_PATH, FILE_ORIGINAL_NAME, FILE_RENAME, MEMBER_NICKNAME,
				 TO_CHAR(FILE_UPLOAD_DATE, 'YYYY-MM-DD') FILE_UPLOAD_DATE
  FROM "UPLOAD_FILE"
  JOIN "MEMBER" ON ("UPLOAD_FILE".MEMBER_NO = "MEMBER".MEMBER_NO)
  WHERE "UPLOAD_FILE".MEMBER_NO = 2
  ORDER BY FILE_NO DESC;
	-- 

	--
	UPDATE UPLOAD_FILE
	SET FILE_PATH = '/myPage/file/'
	WHERE FILE_NO = 2;

	COMMIT;

---------수행완료---------------------------------------------------------------------------------- 

-- 게시판 종류 테이블
CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
); -- 수행됨

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 종류 코드 번호';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판명';

/* 게시판 종류(BOARD_TYPE) 추가 */
CREATE SEQUENCE SEQ_BOARD_CODE NOCACHE;

INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '공지 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '정보 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '자유 게시판');

COMMIT;

SELECT * FROM BOARD_TYPE;

-------------------------------------------------------------------------------------------

/* 게시판 테이블 생성 */
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);


COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부(Y/N)';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 종류 코드 번호';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '작성한 회원 번호(FK)';

--------------------------------------------------------------

-- 게시판 좋아요 테이블(PFK)
CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원 번호(PK)';
COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 번호(PK)';

--------------------------------------------------------------

SELECT * FROM "BOARD_IMG";

-- 게시판 이미지 테이블
CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(200)		NOT NULL, -- 웹에서 접근하는 경로
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지 번호(PK)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지 요청 경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호(PK)';

--------------------------------------------------------------

-- 댓글 테이블
CREATE TABLE "COMMENT" (
	"COMMENT_NO" NUMBER NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER
);



COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호(PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부(Y/N)';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(PK)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모 댓글 번호';

--------------------------------------------------------------

--------------------- PK -----------------------

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
); -- 수행함

ALTER TABLE "UPLOAD_FILE" ADD CONSTRAINT "PK_UPLOAD_FILE" PRIMARY KEY (
	"FILE_NO"
); -- 수행함

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
); -- 수행함

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
); -- 수행함

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
); -- 수행함

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
); -- 수행함

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
); -- 수행함

-------------------- FK -------------------------
-- FK 제약 조건 : 부모의 FK 값만 자식이 사용할 수 있다

ALTER TABLE "UPLOAD_FILE" 
ADD CONSTRAINT "FK_MEMBER_TO_UPLOAD_FILE_1" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO"); 
-- 수행함

ALTER TABLE "BOARD" 
ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" 
FOREIGN KEY ("BOARD_CODE")
REFERENCES "BOARD_TYPE" ("BOARD_CODE");
-- BOARD TYPE 과 BOARD 테이블 연결 
-- 수행함

ALTER TABLE "BOARD" 
ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");
-- 수행함

ALTER TABLE "BOARD_LIKE" 
ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");
-- 수행함

ALTER TABLE "BOARD_LIKE" 
ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" 
FOREIGN KEY ("BOARD_NO")
REFERENCES "BOARD" ("BOARD_NO");
-- 수행함

ALTER TABLE "BOARD_IMG" 
ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" 
FOREIGN KEY ("BOARD_NO")
REFERENCES "BOARD" ("BOARD_NO");
-- 수행함

------
SELECT * FROM BOARD_IMG;
------

ALTER TABLE "COMMENT" 
ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" 
FOREIGN KEY ("BOARD_NO")
REFERENCES "BOARD" ("BOARD_NO");
-- 수행함

ALTER TABLE "COMMENT" 
ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");
-- 수행함

ALTER TABLE "COMMENT" 
ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" 
FOREIGN KEY ("PARENT_COMMENT_NO")
REFERENCES "COMMENT" ("COMMENT_NO");
-- 수행함

---------------------- CHECK -----------------------

-- 게시글 삭제 여부
ALTER TABLE "BOARD" ADD
CONSTRAINT "BOARD_DEL_CHECK"
CHECK("BOARD_DEL_FL" IN ('Y', 'N') );
-- 수행함

-- 댓글 삭제 여부
ALTER TABLE "COMMENT" ADD
CONSTRAINT "COMMENT_DEL_CHECK"
CHECK("COMMENT_DEL_FL" IN ('Y', 'N') );
-- 수행함

---------------------------------------------
/* 게시글 번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; 

BEGIN
	FOR I IN 1..500 LOOP
		
		INSERT INTO "BOARD"
		VALUES(SEQ_BOARD_NO.NEXTVAL,
					 SEQ_BOARD_NO.CURRVAL || '번째 게시글',
					 SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다',
					 DEFAULT, 
					 DEFAULT, 
					 DEFAULT, 
					 DEFAULT,
					 CEIL(DBMS_RANDOM.VALUE(0,3)), -- 0.0 이상 3.0 미만 난수발생시켜 BOARD_TYPE 랜덤 지정
					 1 -- 회원번호
		);

	END LOOP;
END;

COMMIT;

SELECT * FROM "BOARD";

---------------------------------------------------
-- 번호 / 제목[댓글개수] / 작성자닉네임 / 작성일 / 조회수 / 좋아요갯수
SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT,
	
	(SELECT COUNT (*)
	 FROM "COMMENT" C
	 WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT, -- 1. 댓글 개수 부분. 서브쿼리 사용. 현재 BOARD(B)의 BOARD_NO 와 COMMENT 테이블(C) BOARD_NO 이 일치하는 댓글 조회
	 
	 (SELECT COUNT (*) 
	  FROM "BOARD_LIKE" L
	  WHERE L.BOARD_NO = B.BOARD_NO) LIKE_COUNT, -- 2. 좋아요 개수 부분. 서브쿼리 사용. 현재 BOARD(B)의 BOARD_NO 와 BOARD_LIKE 테이블(L) BOARD_NO 이 일치하는 좋아요 수 조회

	 CASE -- 3. 작성일자 표시 부분
	   	 WHEN SYSDATE - BOARD_WRITE_DATE < 1 / 24 / 60 -- 작성일이 1분 미만일 시
	   	 THEN FLOOR ((SYSDATE - BOARD_WRITE_DATE) * 24 * 60 * 60) || '초 전'
			 WHEN SYSDATE - BOARD_WRITE_DATE < 1 / 24 -- 작성일이 1시간 미만일 시
			 THEN FLOOR ((SYSDATE - BOARD_WRITE_DATE) * 24 * 60) || '분 전'
			 WHEN SYSDATE - BOARD_WRITE_DATE < 1 -- 작성일이 하루 미만일 시
		   THEN FLOOR ((SYSDATE - BOARD_WRITE_DATE) * 24) || '시간 전'
	   ELSE TO_CHAR(B.BOARD_WRITE_DATE, 'YYYY-MM-DD') -- 24시간 초과 시 
	 END BOARD_WRITE_DATE
		 
FROM "BOARD" B
JOIN "MEMBER" USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;
---------------------------------------------------
/* 댓글 번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

/* 댓글 ("COMMNET") 테이블에 샘플 데이터 추가*/

BEGIN
	FOR I IN 1..500 LOOP
	
		INSERT INTO "COMMENT"	
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT, DEFAULT,
			CEIL(DBMS_RANDOM.VALUE(0, 500)),
			2,
			NULL
		);

	END LOOP;
END;

SELECT * FROM BOARD;
SELECT * FROM MEMBER;
SELECT * FROM "COMMENT";

COMMIT;

-------- 여기까지 수행 완료 -------------------------
-----------------------------------------------------

/* BOARD_IMG 테이블용 시퀀스 생성 */
CREATE SEQUENCE SEQ_IMG_NO NOCACHE;

/* BOARD_IMG 테이블에 샘플 데이터 삽입 */
INSERT INTO "BOARD_IMG" 
VALUES(SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본1.jpg', 'test1.jpg', 0, 493);

INSERT INTO "BOARD_IMG" 
VALUES(SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본2.jpg', 'test2.jpg', 1, 493);

INSERT INTO "BOARD_IMG" 
VALUES(SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본3.jpg', 'test3.jpg', 2, 493);

INSERT INTO "BOARD_IMG" 
VALUES(SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본4.jpg', 'test4.jpg', 3, 493);

INSERT INTO "BOARD_IMG" 
VALUES(SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본5.jpg', 'test5.jpg', 4, 493);


COMMIT;

SELECT * FROM "BOARD_IMG";



-- 댓글 샘플데이터
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 댓글 1', DEFAULT, DEFAULT,	493, 1, NULL); -- 부모 댓글 없다(NULL) : 레벨 1 댓글이다
			 
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 댓글 2', DEFAULT, DEFAULT,	493, 1, NULL); -- 부모 댓글 없다(NULL) : 레벨 1 댓글이다
			 
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 댓글 3', DEFAULT, DEFAULT,	493, 1, NULL); -- 부모 댓글 없다(NULL) : 레벨 1 댓글이다

SELECT * FROM "COMMENT"
WHERE BOARD_NO = 493
ORDER BY COMMENT_NO DESC;

-- 부모 댓글 1의 자식 댓글
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 1의 자식 1', DEFAULT, DEFAULT,	493, 2, 501);
			 
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 1의 자식 2', DEFAULT, DEFAULT,	493, 2, 501);
			 
-- 부모 댓글 2의 자식 댓글
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 2의 자식 1', DEFAULT, DEFAULT,	493, 2, 502);
			 
-- 부모 댓글 2의 자식 1의 자식 댓글			 
INSERT INTO "COMMENT"	
VALUES(SEQ_COMMENT_NO.NEXTVAL, '부모 2의 자식 1의 자식!!!', DEFAULT, DEFAULT,	493, 2, 506);
			 
COMMIT;

-- 계층형 쿼리 ------------------------------------------------------------------------------

SELECT LEVEL, C.* -- LEVEL : 계층형 쿼리에서 사용하는 가상 컬럼
FROM -- FROM 절 뒤의 서브쿼리 : 조회된 RESULT SET 테이블을 일반 테이블처럼 사용하겠다.
		(
		 SELECT COMMENT_NO, COMMENT_CONTENT, 
						TO_CHAR(COMMENT_WRITE_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') COMMENT_WRITE_DATE,
						BOARD_NO, MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG, PARENT_COMMENT_NO, COMMENT_DEL_FL
		 FROM "COMMENT"
		 JOIN MEMBER USING(MEMBER_NO)
		 WHERE BOARD_NO = 493
		) C -- 조회된 테이블의 별칭을 'C'로 하겠다.
WHERE COMMENT_DEL_FL = 'N' -- 삭제되지 않은 댓글을 조회'하거나'(OR)
OR 0 != ( 
				 -- 부모자식관계가 있는 행들 중 삭제되지 않은 행들의 개수를 세겠다. 
				 -- = 삭제되지 않은 자식댓글의 갯수가 0과 같지 않을 때 
				 -- = 자식댓글 중 하나라도 삭제되지 않은 행이 있다면 그 부모댓글의 행 조회
				 -- = 즉, 부모 댓글이 삭제되더라도 자식 댓글 중 하나라도 삭제되지 않은 댓글이 있다면 일단은 부모 댓글도 조회되긴 해야 함
				 -- = 삭제되지 않은 댓글이거나, 삭제된 댓글이라도 그 아래에 활성 상태의 자식 댓글이 존재한다면 조회
				 SELECT COUNT(*) FROM "COMMENT" SUB
				 WHERE SUB.PARENT_COMMENT_NO = C.COMMENT_NO 
				 AND COMMENT_DEL_FL = 'N'
				)
START WITH PARENT_COMMENT_NO IS NULL -- 부모 댓글이 없는 레벨, 즉, 1벨부터 시작한다.
CONNECT BY PRIOR COMMENT_NO = PARENT_COMMENT_NO -- 조회된 댓글에서 PARENT_COMMENT_NO 컬럼에 다른 댓글의 COMMENT_NO 이 작성되어 있다면 이 둘을 연결하겠다. 
ORDER SIBLINGS BY COMMENT_NO; -- 형제레벨끼리 오름차순으로 정렬

-------------------------------------------------------

/* 좋아요 테이블(BOARD_LIKE) 샘플 데이터 추가 */
INSERT INTO "BOARD_LIKE"
VALUES(2, 2000); -- 2번 회원이 2003번 글에 좋아요를 클릭함

COMMIT;

----------------------------------------------------------

-- SEQ_IMG_NO 시퀀스의 다음 값을 반환하는 함수 생성 (게시글 작성 부분)

-- 전체 드래그 ALT+X
 -- DB 에서 사용할 함수임

-- 만약 아래 INSERT 시행한다고 하면 오류 뜸
-- 왜? 시퀀스는 UNION 으로 연결된 SELECT 에선 사용할 수 없기 때문
-- 누가 먼저인지 파악할 수 없기 때문에 

INSERT INTO "BOARD_IMG"
(
	SELECT SEQ_IMG_NO.NEXTVAL, '경로1', '원본1', '변경1', 1, 2000 FROM DUAL
	UNION
	SELECT SEQ_IMG_NO.NEXTVAL, '경로2', '원본2', '변경2', 1, 2000 FROM DUAL
	UNION
	SELECT SEQ_IMG_NO.NEXTVAL, '경로3', '원본3', '변경3', 1, 2000 FROM DUAL
);

-- 따라서!!
-- 함수를 이용해 NEXTVAL을 발급해주는 기능이 필요함 
-- 아래 확인

CREATE OR REPLACE FUNCTION NEXT_IMG_NO -- NEXT_IMG_NO 의 함수를 생성하거나 덮어쓰겠다.
RETURN NUMBER -- 함수의 반환형은 NUMBER 타입
IS IMG_NO NUMBER; -- 함수에서 이용할 변수명은 IMG_NO으로 NUMBER 타입이다. 
BEGIN -- 여기부터 함수가 하는 일(해당 함수가 호출될 때마다 BEGIN 아래 SQL 이 수행되며 IMG_NO 을 반환 
	SELECT SEQ_IMG_NO.NEXTVAL 
	INTO IMG_NO
	FROM DUAL;
	RETURN IMG_NO;
END;
-- 여기까지 ALT + X 로 실행 후
-- 해당 함수를 게시글 작성 파트 이미지 업로드 mapper 에서 사용 

SELECT NEXT_IMG_NO() FROM DUAL;
-- 위 작성된 함수를 테스트(하나씩 늘어날 것)


-- scheduling 위해 db 이미지 파일 이름 조회 sql

-- 조회 결과로 INSTR(PROFILE_IMG, '/', -1) : PROFILE_IMG 컬럼에서 /를 구분자로 -1(뒤에서)부터 찾아 잘라낸 숫자 반환
-- SUBSTR : 조회 결과를 앞에서부터 (숫자)만큼 잘라 반환 
-- UNION 시 조회하려하는 두 테이블의 각 컬럼값의 데이터가 일치하지 않으면 에러가 발생하기에 통일시켜준다 > CAST
SELECT SUBSTR(PROFILE_IMG, INSTR(PROFILE_IMG, '/', -1) +1 ) "rename" 
FROM "MEMBER"
UNION
SELECT CAST(IMG_RENAME AS VARCHAR2(300)) "rename"
FROM "BOARD_IMG";



---------------------------------------------------------- 여기까지 완료 -----------------------------

/* 채팅 */
CREATE TABLE "CHATTING_ROOM" (
	"CHATTING_ROOM_NO"	NUMBER		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"OPEN_MEMBER"	NUMBER		NOT NULL,
	"PARTICIPANT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_ROOM_NO" IS '채팅방 번호';
COMMENT ON COLUMN "CHATTING_ROOM"."CREATE_DATE" IS '채팅방 생성일';
COMMENT ON COLUMN "CHATTING_ROOM"."OPEN_MEMBER" IS '개설자 회원 번호';
COMMENT ON COLUMN "CHATTING_ROOM"."PARTICIPANT" IS '참여자 회원 번호';

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"MESSAGE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"READ_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"SEND_TIME"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"SENDER_NO"	NUMBER		NOT NULL,
	"CHATTING_ROOM_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '메시지 번호';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메시지 내용';
COMMENT ON COLUMN "MESSAGE"."READ_FL" IS '읽음여부Y/N';
COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '메시지 보낸 시간';
COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '메시지 보낸 회원 번호';
COMMENT ON COLUMN "MESSAGE"."CHATTING_ROOM_NO" IS '채팅방 번호';

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
	"CHATTING_ROOM_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);


ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_1" FOREIGN KEY (
	"OPEN_MEMBER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_2" FOREIGN KEY (
	"PARTICIPANT"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_1" FOREIGN KEY (
	"SENDER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_MESSAGE_1" FOREIGN KEY (
	"CHATTING_ROOM_NO"
)
REFERENCES "CHATTING_ROOM" (
	"CHATTING_ROOM_NO"
);


-- 채팅방 번호 생성 시퀀스
CREATE SEQUENCE SEQ_ROOM_NO NOCACHE;

-- 메시지 번호 생성 시퀀스
CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE;

COMMIT;

/* 로그인한 회원이 참여한 채팅방 목록 조회*/
SELECT CHATTING_ROOM_NO

	,(SELECT MESSAGE_CONTENT FROM 
		(SELECT * FROM MESSAGE M2
		WHERE M2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
		ORDER BY MESSAGE_NO DESC) 
		WHERE ROWNUM = 1) LAST_MESSAGE
		
	,TO_CHAR(
		NVL(
			(SELECT MAX(SEND_TIME) SEND_TIME -- 가장 최신 메시지 
			 FROM MESSAGE M
			 WHERE R.CHATTING_ROOM_NO  = M.CHATTING_ROOM_NO), 
			CREATE_DATE), 
		'YYYY.MM.DD') SEND_TIME
			
	,NVL2( -- NVL2("값", NULL이 아닌 경우, NULL 인 경우)
		(SELECT OPEN_MEMBER 
		 FROM CHATTING_ROOM R2
		 WHERE R2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
		 AND R2.OPEN_MEMBER = 1), -- 값
		 R.PARTICIPANT, -- NULL 이 아닌 경우
		 R.OPEN_MEMBER -- NULL 인 경우
	) TARGET_NO	
		
	,NVL2(
		(SELECT OPEN_MEMBER FROM CHATTING_ROOM R2
		 WHERE R2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
		 AND R2.OPEN_MEMBER = 1),
		(SELECT MEMBER_NICKNAME FROM MEMBER WHERE MEMBER_NO = R.PARTICIPANT),
		(SELECT MEMBER_NICKNAME FROM MEMBER WHERE MEMBER_NO = R.OPEN_MEMBER)
	) TARGET_NICKNAME	
		
	,NVL2(
		(SELECT OPEN_MEMBER FROM CHATTING_ROOM R2
		 WHERE R2.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO
		 AND R2.OPEN_MEMBER = 1),
		(SELECT PROFILE_IMG FROM MEMBER WHERE MEMBER_NO = R.PARTICIPANT),
		(SELECT PROFILE_IMG FROM MEMBER WHERE MEMBER_NO = R.OPEN_MEMBER)
	) TARGET_PROFILE
		
	,(SELECT COUNT(*) FROM MESSAGE M 
		WHERE M.CHATTING_ROOM_NO = R.CHATTING_ROOM_NO 
		AND READ_FL = 'N' AND SENDER_NO != 1) NOT_READ_COUNT
	
	,(SELECT MAX(MESSAGE_NO) SEND_TIME 
		FROM MESSAGE M 
		WHERE R.CHATTING_ROOM_NO  = M.CHATTING_ROOM_NO) MAX_MESSAGE_NO
	
	FROM CHATTING_ROOM R
	WHERE OPEN_MEMBER = 1
	OR PARTICIPANT = 1
	ORDER BY MAX_MESSAGE_NO DESC NULLS LAST;
	
	SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, PROFILE_IMG
	FROM MEMBER
	WHERE (MEMBER_EMAIL LIKE '%유%' OR MEMBER_NICKNAME LIKE '%유%')
	AND MEMBER_DEL_FL = 'N'
	AND MEMBER_NO != 1;

	SELECT * FROM MEMBER;
	SELECT * FROM CHATTING_ROOM;

--------------------------------------------------------

		SELECT BOARD_NAME, BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, (
			SELECT BOARD_MAX(COUNT(*))
			FROM "COMMENT"
			GROUP BY BOARD_NO) COMMENT_COUNT
		FROM "BOARD"
		JOIN "MEMBER" USING(MEMBER_NO)
		JOIN "BOARD_TYPE" USING(BOARD_CODE)
		ORDER BY BOARD_NO DESC
		FETCH FIRST 1 ROWS ONLY;

	SELECT BOARD_NAME, BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, COMMENT_COUNT
	FROM "BOARD"
	JOIN "MEMBER" USING(MEMBER_NO)
	JOIN "BOARD_TYPE" USING(BOARD_CODE)
	WHERE BOARD_NO = (
			SELECT BOARD_NO, COUNT(*) COMMENT_COUNT
			FROM "COMMENT"
			GROUP BY BOARD_NO
			ORDER BY COMMENT_COUNT DESC
			FETCH FIRST 1 ROWS ONLY
		)
	ORDER BY BOARD_NO DESC
	;

	
	
			SELECT BOARD_NO, COUNT(*) COMMENT_COUNT
			FROM "COMMENT"
			GROUP BY BOARD_NO
			ORDER BY COMMENT_COUNT DESC;
	
	
	
	SELECT * FROM BOARD_LIKE;
	SELECT * FROM BOARD B WHERE (SELECT * FROM COMMENT C WHERE BOARD_NO = );
	SELECT * FROM "COMMENT" WHERE MAX(COUNT(BOARD_NO));

		SELECT BOARD_NAME, BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT
		FROM "BOARD"
		JOIN "MEMBER" USING(MEMBER_NO)
		JOIN "BOARD_TYPE" USING(BOARD_CODE)
		WHERE READ_COUNT = (
			SELECT MAX(READ_COUNT) FROM "BOARD"
			)
		ORDER BY BOARD_NO DESC
		FETCH FIRST 1 ROWS ONLY;

			SELECT BOARD_NO, COUNT(*) COMMENT_COUNT
			FROM "COMMENT"
			GROUP BY BOARD_NO
			ORDER BY COMMENT_COUNT DESC;


		SELECT BOARD_NAME, BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, (SELECT COUNT(*) FROM "BOARD_LIKE" L WHERE L.BOARD_NO = B.BOARD_NO) AS LIKE_COUNT
		FROM "BOARD" B
		JOIN "MEMBER" USING(MEMBER_NO)
		JOIN "BOARD_TYPE" USING(BOARD_CODE)
		WHERE BOARD_NO = (
		    SELECT BOARD_NO
		    FROM "BOARD_LIKE"
		    GROUP BY BOARD_NO
		    ORDER BY COUNT(*) DESC
		    FETCH FIRST 1 ROWS ONLY
		)
		ORDER BY BOARD_NO DESC;

SELECT COUNT(*) FROM "COMMENT" C WHERE C.BOARD_NO = B.BOARD_NO) AS COMMENT_COUNT;
SELECT * FROM MEMBER;

